logging:
    level:
        org:
            springframework:
                security:
                    web: DEBUG
                web:
                    server: DEBUG
                    socket: DEBUG
        ru:
            base:
                game: DEBUG
server:
    port: 8097
spring:
    datasource:
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
